CREATE DATABASE library_management;
CREATE USER lib_user WITH PASSWORD 'admin';
GRANT ALL PRIVILEGES ON DATABASE library_management TO lib_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO lib_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lib_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lib_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO lib_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO lib_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO lib_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO lib_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lib_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO lib_user;


